apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dbgpt-chart.fullname" . }}-webserver-claim0
  labels:
    io.kompose.service: webserver-claim0
  {{- include "dbgpt-chart.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.webserverClaim0.storageRequest | quote }}