apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dbgpt-chart.fullname" . }}-webserver-claim1
  labels:
    io.kompose.service: webserver-claim1
  {{- include "dbgpt-chart.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.webserverClaim1.storageRequest | quote }}